[{"name": "test.test_file_count.FileCount.test_calls", "status": "passed", "message": "", "passed": true, "points": ["p02-06.1"], "backtrace": []}, {"name": "test.test_file_count.FileCount.test_first", "status": "failed", "message": "538 != 647 : Wrong number of characters for file 'test.txt'!", "passed": false, "points": ["p02-06.1"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"E:\\koodit\\hy-data-analysis-with-python-summer-2019\\part02-e06_file_count\\test\\test_file_count.py\", line 23, in test_first\n    self.assertEqual(c, 647, msg=\"Wrong number of characters for file 'test.txt'!\")\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 832, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_file_count.FileCount.test_main", "status": "passed", "message": "", "passed": true, "points": ["p02-06.2"], "backtrace": []}]