[{"name": "test.test_radial_fade.RadialFade.test_center", "status": "passed", "message": "", "passed": true, "points": ["p03-12.1"], "backtrace": []}, {"name": "test.test_radial_fade.RadialFade.test_main", "status": "passed", "message": "", "passed": true, "points": ["p03-12.2"], "backtrace": []}, {"name": "test.test_radial_fade.RadialFade.test_radial_distance", "status": "passed", "message": "", "passed": true, "points": ["p03-12.1"], "backtrace": []}, {"name": "test.test_radial_fade.RadialFade.test_radial_fade", "status": "failed", "message": "False is not true : In the center of the image there should be no fading!", "passed": false, "points": ["p03-12.2"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"C:\\Users\\koske\\Documents\\Koodit\\hy-data-analysis-with-python-summer-2019\\part03-e12_radial_fade\\test\\test_radial_fade.py\", line 89, in test_radial_fade\n    msg=\"In the center of the image there should be no fading!\")\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 692, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_radial_fade.RadialFade.test_radial_mask", "status": "failed", "message": "nan not less than or equal to 1.0 : Maximum value in the mask cannot be above 1.0", "passed": false, "points": ["p03-12.2"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"C:\\Users\\koske\\Documents\\Koodit\\hy-data-analysis-with-python-summer-2019\\part03-e12_radial_fade\\test\\test_radial_fade.py\", line 67, in test_radial_mask\n    self.assertLessEqual(rm.max(), 1.0, msg=\"Maximum value in the mask cannot be above 1.0\")\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 1232, in assertLessEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 680, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_radial_fade.RadialFade.test_radial_mask_size_one", "status": "failed", "message": "nan != 1.0 : Are you sure the radial_mask function works correctly for arrays of size 1", "passed": false, "points": ["p03-12.2"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"C:\\Users\\koske\\Documents\\Koodit\\hy-data-analysis-with-python-summer-2019\\part03-e12_radial_fade\\test\\test_radial_fade.py\", line 78, in test_radial_mask_size_one\n    self.assertEqual(rm[0,0], 1.0, msg=\"Are you sure the radial_mask function works correctly for arrays of size 1\")\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 832, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]