[{"name": "test.test_integers_in_brackets.IntegersInBrackets.test_empty", "status": "passed", "message": "", "passed": true, "points": ["p02-01.1"], "backtrace": []}, {"name": "test.test_integers_in_brackets.IntegersInBrackets.test_first", "status": "failed", "message": "Lists differ: [12, 34, 43, 12] != [12, -43, 12]\n\nFirst differing element 1:\n34\n-43\n\nFirst list contains 1 additional elements.\nFirst extra element 3:\n12\n\n- [12, 34, 43, 12]\n?      ^^^^\n\n+ [12, -43, 12]\n?      ^\n : Incorrect result for string   afd [asd] [12 ] [a34]  [\t -43 ]tt [+12]xxx!", "passed": false, "points": ["p02-01.1"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"E:\\koodit\\hy-data-analysis-with-python-summer-2019\\part02-e01_integers_in_brackets\\test\\test_integers_in_brackets.py\", line 20, in test_first\n    self.assertEqual(result, [12, -43, 12], msg=\"Incorrect result for string %s!\" % s)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 1045, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 1027, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 680, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_integers_in_brackets.IntegersInBrackets.test_second", "status": "failed", "message": "Lists differ: [128, 47, 34, 43, 12] != [47, 12]\n\nFirst differing element 0:\n128\n47\n\nFirst list contains 3 additional elements.\nFirst extra element 2:\n34\n\n- [128, 47, 34, 43, 12]\n+ [47, 12] : Incorrect result for string   afd [128+] [47 ] [a34]  [ +-43 ]tt [+12]xxx!", "passed": false, "points": ["p02-01.1"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"E:\\koodit\\hy-data-analysis-with-python-summer-2019\\part02-e01_integers_in_brackets\\test\\test_integers_in_brackets.py\", line 25, in test_second\n    self.assertEqual(result, [47, 12], msg=\"Incorrect result for string %s!\" % s)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 1045, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 1027, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 680, in fail\n    raise self.failureException(msg)\n"]}]