[{"name": "test.test_vector_angles.VectorAngles.test_first", "status": "failed", "message": "\nNot equal to tolerance rtol=1e-07, atol=0\nIncorrect result for vectors [[ 0  0  1]\n [-1  1  0]] and [[0 1 0]\n [1 1 0]]!\nMismatch: 200%\nMax absolute difference: 88.42920367\nMax relative difference: 0.98254671\n x: array(1.570796)\n y: array([90, 90])", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"E:\\koodit\\hy-data-analysis-with-python-summer-2019\\part02-e15_vector_angles\\test\\test_vector_angles.py\", line 26, in test_first\n    err_msg=\"Incorrect result for vectors %s and %s!\" % (A, B))\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\testing\\_private\\utils.py\", line 1493, in assert_allclose\n    verbose=verbose, header=header, equal_nan=equal_nan)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\testing\\_private\\utils.py\", line 819, in assert_array_compare\n    raise AssertionError(msg)\n"]}, {"name": "test.test_vector_angles.VectorAngles.test_main", "status": "passed", "message": "", "passed": true, "points": ["p02-15.1"], "backtrace": []}, {"name": "test.test_vector_angles.VectorAngles.test_zero", "status": "passed", "message": "", "passed": true, "points": ["p02-15.1"], "backtrace": []}]